from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey, Float, Boolean, JSON
from sqlalchemy.orm import relationship
from datetime import datetime
from .connection import Base

# Reuse existing models if they are already defined in the file
# I will only append the new model at the end to avoid any conflicts

class ProductComparison(Base):
    """Stores side-by-side comparison results generated by AI or User"""
    __tablename__ = 'product_comparisons'
    
    id = Column(Integer, primary_key=True)
    query_id = Column(String(255), nullable=True) # ID of the chat or search query
    title = Column(String(255)) # e.g. "Hammer Drill Comparison"
    category = Column(String(100)) # Tools, PPE, Building Materials
    products_json = Column(JSON) # List of product objects being compared
    comparison_table_json = Column(JSON) # The actual table data (headers and rows)
    recommendation = Column(Text) # AI reasoning for the best choice
    missing_info_json = Column(JSON) # Fields that were not found for some suppliers
    confidence_level = Column(String(50)) # High, Medium, Low
    created_by = Column(Integer, ForeignKey('users.id'))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
